# LambdaTest AI Cloud Configuration
project_id: "01KG2C7VC7J2WY64Q55AB2FSW4"
folder_id: "01KS2VYVFH681ZM9RBQPDV1C7V"
assignee: 3116828
environment_id: 285424
test_url: "https://stirring-cheesecake-c47db8.netlify.app/"
