# LambdaTest AI Cloud Configuration
project_id: "01KG2C7VC7J2WY64Q55AB2FSW4"
folder_id: "01KW9KBWEX9Y1VYKC8454PF3G0"
assignee: 3116828
environment_id: 285424
test_url: "https://naveentestmuai-source.github.io/ai-native-quality-validation-sample/#/"
